version: '3.8'

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    environment:
      - SEARXNG_API_URL=http://searxng:8080
    networks:
      - perplexica-network
    restart: unless-stopped
networks:
  perplexica-network: